[Autodelivery] update Continuous Integration pipeline for Java 8 projects from DanySK/centralized-automated-deployer@6b8263b

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -2,7 +2,7 @@ name: CI
 on:
   push:
   schedule:
-    - cron: '0 3 * * SAT'
+    - cron: '0 3 * * SUN'
 
 jobs:
   Build:
@@ -11,12 +11,6 @@ jobs:
         os: [windows, macos, ubuntu]
         jvm_version: [8, 11, 14]
     runs-on: ${{ matrix.os }}-latest
-    env:
-      CI: true
-      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
-      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
-      MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
-      MAVEN_CENTRAL_USERNAME: danysk
     steps:
       - uses: actions/setup-java@v1
         with:
@@ -24,19 +18,50 @@ jobs:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
-      - shell: bash 
-        run: ./gradlew check --parallel
-      - if: ${{ matrix.os == 'ubuntu' && matrix.jvm_version == 8 }}
-        run: 
-          ./gradlew publishMavenCentralPublicationToMavenRepository --parallel \
-          || ./gradlew publishMavenCentralPublicationToMavenRepository --parallel \
-          || ./gradlew publishMavenCentralPublicationToMavenRepository --parallel \
-          || ./gradlew publishMavenCentralPublicationToMavenRepository --parallel \
-          || ./gradlew publishMavenCentralPublicationToMavenRepository --parallel
-      - if: ${{ matrix.os == 'ubuntu' && matrix.jvm_version == 8 }}
-        continue-on-error: true
-        run: 
-          ./gradlew publishPlugin --parallel -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
+      - name: Check
+        shell: bash
+        run: |
+          if [ -x 'build.sh' ]
+          then
+            echo 'Detected custom build instructions'
+            ./build.sh
+          elif [ -x 'gradlew' ]
+          then
+            echo 'Detected gradle wrapper, running ./gradlew clean check --parallel'
+            ./gradlew clean check --parallel
+          elif [ -f 'pom.xml' ]
+          then
+            echo 'Detected Maven pom.xml, running mvn clean install'
+            mvn clean install
+          else
+            echo 'No valid configuration detected, failing'
+            exit 1
+          fi
+      - name: Deploy
+        if: ${{ matrix.os == 'ubuntu' && matrix.jvm_version == 8 }}
+        shell: bash
+        env:
+          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
+          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
+          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
+          MAVEN_CENTRAL_USERNAME: danysk
+        run: |
+          if [ -x 'deploy.sh' ]
+          then
+            echo 'Detected custom deploy instructions'
+            ./deploy.sh
+          elif [ -x 'gradlew' ]
+          then
+            echo 'Detected gradle wrapper, running ./gradlew publish --parallel'
+            ./gradlew publish --parallel
+          elif [ -f 'pom.xml' ]
+          then
+            echo 'Detected Maven pom.xml, running mvn deploy'
+            mvn deploy
+          else
+            echo 'No valid configuration detected, failing'
+            exit 1
+          fi
   CI-Complete:
     needs: Build
     runs-on: ubuntu-latest
